# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-25 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20181022_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=0, null=True, upload_to=b'teacher/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
