# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-26 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='\u540e\u7aef\u5f00\u53d1', max_length=20, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[(b'cj', '\u521d\u7ea7'), (b'zj', '\u4e2d\u7ea7'), (b'gj', '\u9ad8\u7ea7')], max_length=2, verbose_name='\u7b49\u7ea7'),
        ),
    ]
